file = *line

line = whitespace [number] [comment] lf

comment = ";" *comment-char
number = hex-number / dec-number
hex-number = 1*8(seperators hex-digit seperators)
dec-number = "'" 1*(seperators dec-digit seperators)

hex-digit = dec-digit / "A" / "B" / "C" / "D" / "E" / "F"
dec-digit = %x30-39

seperators = *seperator
whitespace = *whitespace-char

lf = %x0A
whitespace-char = %x09-0D / " "
seperator-char = whitespace-char / "-" / "."
comment-char = %x01-09 / %x0B-FF
